export const LANGCODES = [
    { 'name': 'Arabic', 'code': 'ar' },
    { 'name': 'Bulgarian', 'code': 'bg' },
    { 'name': 'Catalan', 'code': 'ca' },
    { 'name': 'Czech', 'code': 'cz' },
    { 'name': 'German', 'code': 'de' },
    { 'name': 'Greek', 'code': 'el' },
    { 'name': 'English', 'code': 'en' },
    { 'name': 'Persian (Farsi)', 'code': 'fa' },
    { 'name': 'Finnish', 'code': 'fi' },
    { 'name': 'French', 'code': 'fr' },
    { 'name': 'Galician', 'code': 'gl' },
    { 'name': 'Croatian', 'code': 'hr' },
    { 'name': 'Hungarian', 'code': 'hu' },
    { 'name': 'Italian', 'code': 'it' },
    { 'name': 'Japanese', 'code': 'ja' },
    { 'name': 'Korean', 'code': 'kr' },
    { 'name': 'Latvian', 'code': 'la' },
    { 'name': 'Lithuanian', 'code': 'lt' },
    { 'name': 'Macedonian', 'code': 'mk' },
    { 'name': 'Dutch', 'code': 'nl' },
    { 'name': 'Polish', 'code': 'pl' },
    { 'name': 'Portuguese', 'code': 'pt' },
    { 'name': 'Romanian', 'code': 'ro' },
    { 'name': 'Russian', 'code': 'ru' },
    { 'name': 'Swedish', 'code': 'se' },
    { 'name': 'Slovak', 'code': 'sk' },
    { 'name': 'Slovenian', 'code': 'sl' },
    { 'name': 'Spanish', 'code': 'es' },
    { 'name': 'Turkish', 'code': 'tr' },
    { 'name': 'Ukrainian', 'code': 'ua' },
    { 'name': 'Vietnamese', 'code': 'vi' },
    { 'name': 'Chinese Simplified', 'code': 'zh_cn' },
    { 'name': 'Chinese Traditional', 'code': 'zh_tw' }
];